sections:
  main:
    display: Main
    fields:
      -
        handle: title
        field:
          type: text
          required: true
          validate:
            - required
      -
        handle: image
        field:
          mode: list
          container: assets
          restrict: false
          allow_uploads: true
          show_filename: true
          max_files: 1
          display: Image
          type: assets
          icon: assets
          listable: hidden
          instructions_position: above
          visibility: visible
          always_save: false
      -
        handle: description
        field:
          character_limit: '700'
          antlers: false
          display: Description
          type: textarea
          icon: textarea
          listable: hidden
          instructions_position: above
          visibility: visible
          always_save: false
  sidebar:
    display: Sidebar
    fields:
      -
        handle: slug
        field:
          type: slug
          localizable: true
      -
        handle: cable_type
        field:
          type: terms
          taxonomies:
            - cable_type
          display: 'Cable type'
          mode: select
          instructions_position: above
          listable: hidden
          visibility: visible
          always_save: false
          max_items: 1
          create: true
          validate:
            - required
      -
        handle: base-price
        field:
          type: money
          display: 'Base price'
          instructions_position: above
          listable: hidden
          visibility: visible
          always_save: false
          read_only: false
          validate:
            - required
      -
        handle: price_per_meter
        field:
          read_only: false
          display: 'Price per meter'
          type: money
          icon: generic
          listable: hidden
          instructions_position: above
          visibility: visible
          always_save: false
          validate:
            - required
      -
        handle: tax_category
        field:
          type: tax_category
          display: 'Tax Category'
          max_items: 1
          mode: select
      -
        handle: price
        field:
          type: money
          display: Price
title: Product
