title: Interconnect
tabs:
  main:
    display: Main
    sections:
      -
        fields:
          -
            handle: title
            field:
              type: text
              required: true
              validate:
                - required
          -
            handle: image
            field:
              mode: list
              container: assets
              restrict: false
              allow_uploads: true
              show_filename: true
              max_files: 1
              display: Image
              type: assets
              icon: assets
              listable: hidden
              instructions_position: above
              visibility: visible
              always_save: false
          -
            handle: description
            field:
              character_limit: '700'
              antlers: false
              display: Description
              type: textarea
              icon: textarea
              listable: hidden
              instructions_position: above
              visibility: visible
              always_save: false
  sidebar:
    display: Sidebar
    sections:
      -
        fields:
          -
            handle: slug
            field:
              type: slug
              localizable: true
          -
            handle: base_price
            field:
              display: 'Base price'
              type: integer
              icon: integer
              listable: hidden
              instructions_position: above
              visibility: visible
              always_save: false
          -
            handle: price_per_meter
            field:
              display: 'Price per meter'
              type: integer
              icon: integer
              listable: hidden
              instructions_position: above
              visibility: visible
              always_save: false
          -
            handle: price_for_0_5m
            field:
              display: 'Price for 0.5M'
              type: integer
              icon: integer
              listable: hidden
              instructions_position: above
              visibility: visible
              always_save: false
          -
            handle: price_for_0_5_meter_xlr
            field:
              display: 'Price for 0.5 meter XLR'
              type: integer
              icon: integer
              listable: hidden
              instructions_position: above
              visibility: visible
              always_save: false
          -
            handle: price_for_1_meter
            field:
              display: 'Price for 1 meter'
              type: integer
              icon: integer
              listable: hidden
              instructions_position: above
              visibility: visible
              always_save: false
          -
            handle: price_for_1_meter_xlr
            field:
              display: 'Price for 1 meter XLR'
              type: integer
              icon: integer
              listable: hidden
              instructions_position: above
              visibility: visible
              always_save: false
          -
            handle: price_for_1_5_meter
            field:
              display: 'Price for 1.5 meter'
              type: integer
              icon: integer
              listable: hidden
              instructions_position: above
              visibility: visible
              always_save: false
          -
            handle: price_for_1_5_meter_xlr
            field:
              display: 'Price for 1.5 meter XLR'
              type: integer
              icon: integer
              listable: hidden
              instructions_position: above
              visibility: visible
              always_save: false
          -
            handle: price_for_2_meter
            field:
              display: 'Price for 2 meter'
              type: integer
              icon: integer
              listable: hidden
              instructions_position: above
              visibility: visible
              always_save: false
          -
            handle: price_for_2_meter_xlr
            field:
              display: 'Price for 2 meter XLR'
              type: integer
              icon: integer
              listable: hidden
              instructions_position: above
              visibility: visible
              always_save: false
          -
            handle: price_for_3_meter
            field:
              display: 'Price for 3 meter'
              type: integer
              icon: integer
              listable: hidden
              instructions_position: above
              visibility: visible
              always_save: false
          -
            handle: price_for_3_meter_xlr
            field:
              display: 'Price for 3 meter XLR'
              type: integer
              icon: integer
              listable: hidden
              instructions_position: above
              visibility: visible
              always_save: false
          -
            handle: price_for_4_meter
            field:
              display: 'Price for 4 meter'
              type: integer
              icon: integer
              listable: hidden
              instructions_position: above
              visibility: visible
              always_save: false
          -
            handle: price_for_4_meter_xlr
            field:
              display: 'Price for 4 meter XLR'
              type: integer
              icon: integer
              listable: hidden
              instructions_position: above
              visibility: visible
              always_save: false
          -
            handle: price_for_5_meter
            field:
              display: 'Price for 5 meter'
              type: integer
              icon: integer
              listable: hidden
              instructions_position: above
              visibility: visible
              always_save: false
          -
            handle: price_for_5_meter_xlr
            field:
              display: 'Price for 5 meter XLR'
              type: integer
              icon: integer
              listable: hidden
              instructions_position: above
              visibility: visible
              always_save: false
