title: Interconnects
template: productdetail
layout: layout
revisions: false
route: '{{slug}}'
sort_dir: asc
date_behavior:
  past: public
  future: private
preview_targets:
  -
    label: Entry
    url: '{permalink}'
structure:
  root: false
  max_depth: 1
