title: Interconnects
template: productdetail
layout: layout
mount: 42720ef5-4dab-496c-b91a-39be6fd69f57
revisions: false
route: 'interconnects/{slug}'
sort_dir: asc
date_behavior:
  past: public
  future: private
preview_targets:
  -
    label: Entry
    url: '{permalink}'
    refresh: true
structure:
  root: false
  max_depth: 1
