title: Interconnect
updated_by: 63f13f7c-2a11-499f-b033-ad0f353c2031
updated_at: 1667407384
blueprint: cable_type
description: 'Discover greater reality, layering, atmospherics, and naturalness ArgentPur offers three tiers of internconnects, available both single ended and balanced XLR.'
